source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'testData_Example', :exclusive => true do
  pod 'testData', :path => '../'
end

target 'testData_Tests', :exclusive => true do
  pod 'testData', :path => '../'

  
end
